const express = require("express");

const app = express();

app.get("/search/users", (req, res) => {
  // res.set("Access-Control-Allow-Origin", "*");

  res.json({
    total_count: 772,
    incomplete_results: false,
    items: [
      {
        login: "yyx",
        id: 1514965,
        node_id: "MDQ6VXNlcjE1MTQ5NjU=",
        avatar_url: "https://avatars0.githubusercontent.com/u/1514965?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/yyx",
        html_url: "https://github.com/yyx",
        followers_url: "https://api.github.com/users/yyx/followers",
        following_url: "https://api.github.com/users/yyx/following{/other_user}",
        gists_url: "https://api.github.com/users/yyx/gists{/gist_id}",
        starred_url: "https://api.github.com/users/yyx/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/yyx/subscriptions",
        organizations_url: "https://api.github.com/users/yyx/orgs",
        repos_url: "https://api.github.com/users/yyx/repos",
        events_url: "https://api.github.com/users/yyx/events{/privacy}",
        received_events_url: "https://api.github.com/users/yyx/received_events",
        type: "User",
        site_admin: false,
        score: 1
      },
      {
        login: "yyx990803",
        id: 499550,
        node_id: "MDQ6VXNlcjQ5OTU1MA==",
        avatar_url: "https://avatars1.githubusercontent.com/u/499550?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/yyx990803",
        html_url: "https://github.com/yyx990803",
        followers_url: "https://api.github.com/users/yyx990803/followers",
        following_url: "https://api.github.com/users/yyx990803/following{/other_user}",
        gists_url: "https://api.github.com/users/yyx990803/gists{/gist_id}",
        starred_url: "https://api.github.com/users/yyx990803/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/yyx990803/subscriptions",
        organizations_url: "https://api.github.com/users/yyx990803/orgs",
        repos_url: "https://api.github.com/users/yyx990803/repos",
        events_url: "https://api.github.com/users/yyx990803/events{/privacy}",
        received_events_url: "https://api.github.com/users/yyx990803/received_events",
        type: "User",
        site_admin: false,
        score: 1
      },
      {
        login: "coderyyx",
        id: 19465842,
        node_id: "MDQ6VXNlcjE5NDY1ODQy",
        avatar_url: "https://avatars3.githubusercontent.com/u/19465842?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/coderyyx",
        html_url: "https://github.com/coderyyx",
        followers_url: "https://api.github.com/users/coderyyx/followers",
        following_url: "https://api.github.com/users/coderyyx/following{/other_user}",
        gists_url: "https://api.github.com/users/coderyyx/gists{/gist_id}",
        starred_url: "https://api.github.com/users/coderyyx/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/coderyyx/subscriptions",
        organizations_url: "https://api.github.com/users/coderyyx/orgs",
        repos_url: "https://api.github.com/users/coderyyx/repos",
        events_url: "https://api.github.com/users/coderyyx/events{/privacy}",
        received_events_url: "https://api.github.com/users/coderyyx/received_events",
        type: "User",
        site_admin: false,
        score: 1
      },
      {
        login: "yyxida",
        id: 22792135,
        node_id: "MDQ6VXNlcjIyNzkyMTM1",
        avatar_url: "https://avatars3.githubusercontent.com/u/22792135?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/yyxida",
        html_url: "https://github.com/yyxida",
        followers_url: "https://api.github.com/users/yyxida/followers",
        following_url: "https://api.github.com/users/yyxida/following{/other_user}",
        gists_url: "https://api.github.com/users/yyxida/gists{/gist_id}",
        starred_url: "https://api.github.com/users/yyxida/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/yyxida/subscriptions",
        organizations_url: "https://api.github.com/users/yyxida/orgs",
        repos_url: "https://api.github.com/users/yyxida/repos",
        events_url: "https://api.github.com/users/yyxida/events{/privacy}",
        received_events_url: "https://api.github.com/users/yyxida/received_events",
        type: "User",
        site_admin: false,
        score: 1
      },
      {
        login: "yyxx2z",
        id: 9780974,
        node_id: "MDQ6VXNlcjk3ODA5NzQ=",
        avatar_url: "https://avatars0.githubusercontent.com/u/9780974?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/yyxx2z",
        html_url: "https://github.com/yyxx2z",
        followers_url: "https://api.github.com/users/yyxx2z/followers",
        following_url: "https://api.github.com/users/yyxx2z/following{/other_user}",
        gists_url: "https://api.github.com/users/yyxx2z/gists{/gist_id}",
        starred_url: "https://api.github.com/users/yyxx2z/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/yyxx2z/subscriptions",
        organizations_url: "https://api.github.com/users/yyxx2z/orgs",
        repos_url: "https://api.github.com/users/yyxx2z/repos",
        events_url: "https://api.github.com/users/yyxx2z/events{/privacy}",
        received_events_url: "https://api.github.com/users/yyxx2z/received_events",
        type: "User",
        site_admin: false,
        score: 1
      },
      {
        login: "yyxyz",
        id: 8804087,
        node_id: "MDQ6VXNlcjg4MDQwODc=",
        avatar_url: "https://avatars1.githubusercontent.com/u/8804087?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/yyxyz",
        html_url: "https://github.com/yyxyz",
        followers_url: "https://api.github.com/users/yyxyz/followers",
        following_url: "https://api.github.com/users/yyxyz/following{/other_user}",
        gists_url: "https://api.github.com/users/yyxyz/gists{/gist_id}",
        starred_url: "https://api.github.com/users/yyxyz/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/yyxyz/subscriptions",
        organizations_url: "https://api.github.com/users/yyxyz/orgs",
        repos_url: "https://api.github.com/users/yyxyz/repos",
        events_url: "https://api.github.com/users/yyxyz/events{/privacy}",
        received_events_url: "https://api.github.com/users/yyxyz/received_events",
        type: "User",
        site_admin: false,
        score: 1
      },
      {
        login: "yyx290799684",
        id: 11473783,
        node_id: "MDQ6VXNlcjExNDczNzgz",
        avatar_url: "https://avatars0.githubusercontent.com/u/11473783?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/yyx290799684",
        html_url: "https://github.com/yyx290799684",
        followers_url: "https://api.github.com/users/yyx290799684/followers",
        following_url: "https://api.github.com/users/yyx290799684/following{/other_user}",
        gists_url: "https://api.github.com/users/yyx290799684/gists{/gist_id}",
        starred_url: "https://api.github.com/users/yyx290799684/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/yyx290799684/subscriptions",
        organizations_url: "https://api.github.com/users/yyx290799684/orgs",
        repos_url: "https://api.github.com/users/yyx290799684/repos",
        events_url: "https://api.github.com/users/yyx290799684/events{/privacy}",
        received_events_url: "https://api.github.com/users/yyx290799684/received_events",
        type: "User",
        site_admin: false,
        score: 1
      },
      {
        login: "crysisx",
        id: 7436762,
        node_id: "MDQ6VXNlcjc0MzY3NjI=",
        avatar_url: "https://avatars3.githubusercontent.com/u/7436762?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/crysisx",
        html_url: "https://github.com/crysisx",
        followers_url: "https://api.github.com/users/crysisx/followers",
        following_url: "https://api.github.com/users/crysisx/following{/other_user}",
        gists_url: "https://api.github.com/users/crysisx/gists{/gist_id}",
        starred_url: "https://api.github.com/users/crysisx/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/crysisx/subscriptions",
        organizations_url: "https://api.github.com/users/crysisx/orgs",
        repos_url: "https://api.github.com/users/crysisx/repos",
        events_url: "https://api.github.com/users/crysisx/events{/privacy}",
        received_events_url: "https://api.github.com/users/crysisx/received_events",
        type: "User",
        site_admin: false,
        score: 1
      },
      {
        login: "yyxx9988",
        id: 13196890,
        node_id: "MDQ6VXNlcjEzMTk2ODkw",
        avatar_url: "https://avatars3.githubusercontent.com/u/13196890?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/yyxx9988",
        html_url: "https://github.com/yyxx9988",
        followers_url: "https://api.github.com/users/yyxx9988/followers",
        following_url: "https://api.github.com/users/yyxx9988/following{/other_user}",
        gists_url: "https://api.github.com/users/yyxx9988/gists{/gist_id}",
        starred_url: "https://api.github.com/users/yyxx9988/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/yyxx9988/subscriptions",
        organizations_url: "https://api.github.com/users/yyxx9988/orgs",
        repos_url: "https://api.github.com/users/yyxx9988/repos",
        events_url: "https://api.github.com/users/yyxx9988/events{/privacy}",
        received_events_url: "https://api.github.com/users/yyxx9988/received_events",
        type: "User",
        site_admin: false,
        score: 1
      },
      {
        login: "yyxhdy",
        id: 20468886,
        node_id: "MDQ6VXNlcjIwNDY4ODg2",
        avatar_url: "https://avatars0.githubusercontent.com/u/20468886?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/yyxhdy",
        html_url: "https://github.com/yyxhdy",
        followers_url: "https://api.github.com/users/yyxhdy/followers",
        following_url: "https://api.github.com/users/yyxhdy/following{/other_user}",
        gists_url: "https://api.github.com/users/yyxhdy/gists{/gist_id}",
        starred_url: "https://api.github.com/users/yyxhdy/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/yyxhdy/subscriptions",
        organizations_url: "https://api.github.com/users/yyxhdy/orgs",
        repos_url: "https://api.github.com/users/yyxhdy/repos",
        events_url: "https://api.github.com/users/yyxhdy/events{/privacy}",
        received_events_url: "https://api.github.com/users/yyxhdy/received_events",
        type: "User",
        site_admin: false,
        score: 1
      },
      {
        login: "yyxiao",
        id: 12438636,
        node_id: "MDQ6VXNlcjEyNDM4NjM2",
        avatar_url: "https://avatars0.githubusercontent.com/u/12438636?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/yyxiao",
        html_url: "https://github.com/yyxiao",
        followers_url: "https://api.github.com/users/yyxiao/followers",
        following_url: "https://api.github.com/users/yyxiao/following{/other_user}",
        gists_url: "https://api.github.com/users/yyxiao/gists{/gist_id}",
        starred_url: "https://api.github.com/users/yyxiao/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/yyxiao/subscriptions",
        organizations_url: "https://api.github.com/users/yyxiao/orgs",
        repos_url: "https://api.github.com/users/yyxiao/repos",
        events_url: "https://api.github.com/users/yyxiao/events{/privacy}",
        received_events_url: "https://api.github.com/users/yyxiao/received_events",
        type: "User",
        site_admin: false,
        score: 1
      },
      {
        login: "yyx219",
        id: 28554688,
        node_id: "MDQ6VXNlcjI4NTU0Njg4",
        avatar_url: "https://avatars1.githubusercontent.com/u/28554688?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/yyx219",
        html_url: "https://github.com/yyx219",
        followers_url: "https://api.github.com/users/yyx219/followers",
        following_url: "https://api.github.com/users/yyx219/following{/other_user}",
        gists_url: "https://api.github.com/users/yyx219/gists{/gist_id}",
        starred_url: "https://api.github.com/users/yyx219/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/yyx219/subscriptions",
        organizations_url: "https://api.github.com/users/yyx219/orgs",
        repos_url: "https://api.github.com/users/yyx219/repos",
        events_url: "https://api.github.com/users/yyx219/events{/privacy}",
        received_events_url: "https://api.github.com/users/yyx219/received_events",
        type: "User",
        site_admin: false,
        score: 1
      },
      {
        login: "yyxxzz",
        id: 11434309,
        node_id: "MDQ6VXNlcjExNDM0MzA5",
        avatar_url: "https://avatars2.githubusercontent.com/u/11434309?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/yyxxzz",
        html_url: "https://github.com/yyxxzz",
        followers_url: "https://api.github.com/users/yyxxzz/followers",
        following_url: "https://api.github.com/users/yyxxzz/following{/other_user}",
        gists_url: "https://api.github.com/users/yyxxzz/gists{/gist_id}",
        starred_url: "https://api.github.com/users/yyxxzz/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/yyxxzz/subscriptions",
        organizations_url: "https://api.github.com/users/yyxxzz/orgs",
        repos_url: "https://api.github.com/users/yyxxzz/repos",
        events_url: "https://api.github.com/users/yyxxzz/events{/privacy}",
        received_events_url: "https://api.github.com/users/yyxxzz/received_events",
        type: "User",
        site_admin: false,
        score: 1
      },
      {
        login: "yyxiongzju",
        id: 20729758,
        node_id: "MDQ6VXNlcjIwNzI5NzU4",
        avatar_url: "https://avatars3.githubusercontent.com/u/20729758?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/yyxiongzju",
        html_url: "https://github.com/yyxiongzju",
        followers_url: "https://api.github.com/users/yyxiongzju/followers",
        following_url: "https://api.github.com/users/yyxiongzju/following{/other_user}",
        gists_url: "https://api.github.com/users/yyxiongzju/gists{/gist_id}",
        starred_url: "https://api.github.com/users/yyxiongzju/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/yyxiongzju/subscriptions",
        organizations_url: "https://api.github.com/users/yyxiongzju/orgs",
        repos_url: "https://api.github.com/users/yyxiongzju/repos",
        events_url: "https://api.github.com/users/yyxiongzju/events{/privacy}",
        received_events_url: "https://api.github.com/users/yyxiongzju/received_events",
        type: "User",
        site_admin: false,
        score: 1
      },
      {
        login: "YYxDeveloper",
        id: 16028562,
        node_id: "MDQ6VXNlcjE2MDI4NTYy",
        avatar_url: "https://avatars1.githubusercontent.com/u/16028562?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/YYxDeveloper",
        html_url: "https://github.com/YYxDeveloper",
        followers_url: "https://api.github.com/users/YYxDeveloper/followers",
        following_url: "https://api.github.com/users/YYxDeveloper/following{/other_user}",
        gists_url: "https://api.github.com/users/YYxDeveloper/gists{/gist_id}",
        starred_url: "https://api.github.com/users/YYxDeveloper/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/YYxDeveloper/subscriptions",
        organizations_url: "https://api.github.com/users/YYxDeveloper/orgs",
        repos_url: "https://api.github.com/users/YYxDeveloper/repos",
        events_url: "https://api.github.com/users/YYxDeveloper/events{/privacy}",
        received_events_url: "https://api.github.com/users/YYxDeveloper/received_events",
        type: "User",
        site_admin: false,
        score: 1
      },
      {
        login: "yyxd",
        id: 32361127,
        node_id: "MDQ6VXNlcjMyMzYxMTI3",
        avatar_url: "https://avatars1.githubusercontent.com/u/32361127?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/yyxd",
        html_url: "https://github.com/yyxd",
        followers_url: "https://api.github.com/users/yyxd/followers",
        following_url: "https://api.github.com/users/yyxd/following{/other_user}",
        gists_url: "https://api.github.com/users/yyxd/gists{/gist_id}",
        starred_url: "https://api.github.com/users/yyxd/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/yyxd/subscriptions",
        organizations_url: "https://api.github.com/users/yyxd/orgs",
        repos_url: "https://api.github.com/users/yyxd/repos",
        events_url: "https://api.github.com/users/yyxd/events{/privacy}",
        received_events_url: "https://api.github.com/users/yyxd/received_events",
        type: "User",
        site_admin: false,
        score: 1
      },
      {
        login: "yyxndd",
        id: 20489069,
        node_id: "MDQ6VXNlcjIwNDg5MDY5",
        avatar_url: "https://avatars2.githubusercontent.com/u/20489069?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/yyxndd",
        html_url: "https://github.com/yyxndd",
        followers_url: "https://api.github.com/users/yyxndd/followers",
        following_url: "https://api.github.com/users/yyxndd/following{/other_user}",
        gists_url: "https://api.github.com/users/yyxndd/gists{/gist_id}",
        starred_url: "https://api.github.com/users/yyxndd/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/yyxndd/subscriptions",
        organizations_url: "https://api.github.com/users/yyxndd/orgs",
        repos_url: "https://api.github.com/users/yyxndd/repos",
        events_url: "https://api.github.com/users/yyxndd/events{/privacy}",
        received_events_url: "https://api.github.com/users/yyxndd/received_events",
        type: "User",
        site_admin: false,
        score: 1
      },
      {
        login: "YYXuelangwang",
        id: 16287226,
        node_id: "MDQ6VXNlcjE2Mjg3MjI2",
        avatar_url: "https://avatars2.githubusercontent.com/u/16287226?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/YYXuelangwang",
        html_url: "https://github.com/YYXuelangwang",
        followers_url: "https://api.github.com/users/YYXuelangwang/followers",
        following_url: "https://api.github.com/users/YYXuelangwang/following{/other_user}",
        gists_url: "https://api.github.com/users/YYXuelangwang/gists{/gist_id}",
        starred_url: "https://api.github.com/users/YYXuelangwang/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/YYXuelangwang/subscriptions",
        organizations_url: "https://api.github.com/users/YYXuelangwang/orgs",
        repos_url: "https://api.github.com/users/YYXuelangwang/repos",
        events_url: "https://api.github.com/users/YYXuelangwang/events{/privacy}",
        received_events_url: "https://api.github.com/users/YYXuelangwang/received_events",
        type: "User",
        site_admin: false,
        score: 1
      },
      {
        login: "yyx0103",
        id: 58345957,
        node_id: "MDQ6VXNlcjU4MzQ1OTU3",
        avatar_url: "https://avatars2.githubusercontent.com/u/58345957?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/yyx0103",
        html_url: "https://github.com/yyx0103",
        followers_url: "https://api.github.com/users/yyx0103/followers",
        following_url: "https://api.github.com/users/yyx0103/following{/other_user}",
        gists_url: "https://api.github.com/users/yyx0103/gists{/gist_id}",
        starred_url: "https://api.github.com/users/yyx0103/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/yyx0103/subscriptions",
        organizations_url: "https://api.github.com/users/yyx0103/orgs",
        repos_url: "https://api.github.com/users/yyx0103/repos",
        events_url: "https://api.github.com/users/yyx0103/events{/privacy}",
        received_events_url: "https://api.github.com/users/yyx0103/received_events",
        type: "User",
        site_admin: false,
        score: 1
      },
      {
        login: "Yyx2626",
        id: 8017356,
        node_id: "MDQ6VXNlcjgwMTczNTY=",
        avatar_url: "https://avatars2.githubusercontent.com/u/8017356?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/Yyx2626",
        html_url: "https://github.com/Yyx2626",
        followers_url: "https://api.github.com/users/Yyx2626/followers",
        following_url: "https://api.github.com/users/Yyx2626/following{/other_user}",
        gists_url: "https://api.github.com/users/Yyx2626/gists{/gist_id}",
        starred_url: "https://api.github.com/users/Yyx2626/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/Yyx2626/subscriptions",
        organizations_url: "https://api.github.com/users/Yyx2626/orgs",
        repos_url: "https://api.github.com/users/Yyx2626/repos",
        events_url: "https://api.github.com/users/Yyx2626/events{/privacy}",
        received_events_url: "https://api.github.com/users/Yyx2626/received_events",
        type: "User",
        site_admin: false,
        score: 1
      },
      {
        login: "yyx1107",
        id: 50829614,
        node_id: "MDQ6VXNlcjUwODI5NjE0",
        avatar_url: "https://avatars2.githubusercontent.com/u/50829614?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/yyx1107",
        html_url: "https://github.com/yyx1107",
        followers_url: "https://api.github.com/users/yyx1107/followers",
        following_url: "https://api.github.com/users/yyx1107/following{/other_user}",
        gists_url: "https://api.github.com/users/yyx1107/gists{/gist_id}",
        starred_url: "https://api.github.com/users/yyx1107/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/yyx1107/subscriptions",
        organizations_url: "https://api.github.com/users/yyx1107/orgs",
        repos_url: "https://api.github.com/users/yyx1107/repos",
        events_url: "https://api.github.com/users/yyx1107/events{/privacy}",
        received_events_url: "https://api.github.com/users/yyx1107/received_events",
        type: "User",
        site_admin: false,
        score: 1
      },
      {
        login: "yyxql",
        id: 20412685,
        node_id: "MDQ6VXNlcjIwNDEyNjg1",
        avatar_url: "https://avatars0.githubusercontent.com/u/20412685?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/yyxql",
        html_url: "https://github.com/yyxql",
        followers_url: "https://api.github.com/users/yyxql/followers",
        following_url: "https://api.github.com/users/yyxql/following{/other_user}",
        gists_url: "https://api.github.com/users/yyxql/gists{/gist_id}",
        starred_url: "https://api.github.com/users/yyxql/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/yyxql/subscriptions",
        organizations_url: "https://api.github.com/users/yyxql/orgs",
        repos_url: "https://api.github.com/users/yyxql/repos",
        events_url: "https://api.github.com/users/yyxql/events{/privacy}",
        received_events_url: "https://api.github.com/users/yyxql/received_events",
        type: "User",
        site_admin: false,
        score: 1
      },
      {
        login: "yyxt11",
        id: 10813662,
        node_id: "MDQ6VXNlcjEwODEzNjYy",
        avatar_url: "https://avatars0.githubusercontent.com/u/10813662?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/yyxt11",
        html_url: "https://github.com/yyxt11",
        followers_url: "https://api.github.com/users/yyxt11/followers",
        following_url: "https://api.github.com/users/yyxt11/following{/other_user}",
        gists_url: "https://api.github.com/users/yyxt11/gists{/gist_id}",
        starred_url: "https://api.github.com/users/yyxt11/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/yyxt11/subscriptions",
        organizations_url: "https://api.github.com/users/yyxt11/orgs",
        repos_url: "https://api.github.com/users/yyxt11/repos",
        events_url: "https://api.github.com/users/yyxt11/events{/privacy}",
        received_events_url: "https://api.github.com/users/yyxt11/received_events",
        type: "User",
        site_admin: false,
        score: 1
      },
      {
        login: "yyxgiser",
        id: 39320776,
        node_id: "MDQ6VXNlcjM5MzIwNzc2",
        avatar_url: "https://avatars2.githubusercontent.com/u/39320776?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/yyxgiser",
        html_url: "https://github.com/yyxgiser",
        followers_url: "https://api.github.com/users/yyxgiser/followers",
        following_url: "https://api.github.com/users/yyxgiser/following{/other_user}",
        gists_url: "https://api.github.com/users/yyxgiser/gists{/gist_id}",
        starred_url: "https://api.github.com/users/yyxgiser/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/yyxgiser/subscriptions",
        organizations_url: "https://api.github.com/users/yyxgiser/orgs",
        repos_url: "https://api.github.com/users/yyxgiser/repos",
        events_url: "https://api.github.com/users/yyxgiser/events{/privacy}",
        received_events_url: "https://api.github.com/users/yyxgiser/received_events",
        type: "User",
        site_admin: false,
        score: 1
      },
      {
        login: "YYx00xZZ",
        id: 47386361,
        node_id: "MDQ6VXNlcjQ3Mzg2MzYx",
        avatar_url: "https://avatars0.githubusercontent.com/u/47386361?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/YYx00xZZ",
        html_url: "https://github.com/YYx00xZZ",
        followers_url: "https://api.github.com/users/YYx00xZZ/followers",
        following_url: "https://api.github.com/users/YYx00xZZ/following{/other_user}",
        gists_url: "https://api.github.com/users/YYx00xZZ/gists{/gist_id}",
        starred_url: "https://api.github.com/users/YYx00xZZ/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/YYx00xZZ/subscriptions",
        organizations_url: "https://api.github.com/users/YYx00xZZ/orgs",
        repos_url: "https://api.github.com/users/YYx00xZZ/repos",
        events_url: "https://api.github.com/users/YYx00xZZ/events{/privacy}",
        received_events_url: "https://api.github.com/users/YYx00xZZ/received_events",
        type: "User",
        site_admin: false,
        score: 1
      },
      {
        login: "yyx8671",
        id: 17119749,
        node_id: "MDQ6VXNlcjE3MTE5NzQ5",
        avatar_url: "https://avatars3.githubusercontent.com/u/17119749?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/yyx8671",
        html_url: "https://github.com/yyx8671",
        followers_url: "https://api.github.com/users/yyx8671/followers",
        following_url: "https://api.github.com/users/yyx8671/following{/other_user}",
        gists_url: "https://api.github.com/users/yyx8671/gists{/gist_id}",
        starred_url: "https://api.github.com/users/yyx8671/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/yyx8671/subscriptions",
        organizations_url: "https://api.github.com/users/yyx8671/orgs",
        repos_url: "https://api.github.com/users/yyx8671/repos",
        events_url: "https://api.github.com/users/yyx8671/events{/privacy}",
        received_events_url: "https://api.github.com/users/yyx8671/received_events",
        type: "User",
        site_admin: false,
        score: 1
      },
      {
        login: "barriezh",
        id: 14339827,
        node_id: "MDQ6VXNlcjE0MzM5ODI3",
        avatar_url: "https://avatars0.githubusercontent.com/u/14339827?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/barriezh",
        html_url: "https://github.com/barriezh",
        followers_url: "https://api.github.com/users/barriezh/followers",
        following_url: "https://api.github.com/users/barriezh/following{/other_user}",
        gists_url: "https://api.github.com/users/barriezh/gists{/gist_id}",
        starred_url: "https://api.github.com/users/barriezh/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/barriezh/subscriptions",
        organizations_url: "https://api.github.com/users/barriezh/orgs",
        repos_url: "https://api.github.com/users/barriezh/repos",
        events_url: "https://api.github.com/users/barriezh/events{/privacy}",
        received_events_url: "https://api.github.com/users/barriezh/received_events",
        type: "User",
        site_admin: false,
        score: 1
      },
      {
        login: "y111x",
        id: 13828098,
        node_id: "MDQ6VXNlcjEzODI4MDk4",
        avatar_url: "https://avatars0.githubusercontent.com/u/13828098?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/y111x",
        html_url: "https://github.com/y111x",
        followers_url: "https://api.github.com/users/y111x/followers",
        following_url: "https://api.github.com/users/y111x/following{/other_user}",
        gists_url: "https://api.github.com/users/y111x/gists{/gist_id}",
        starred_url: "https://api.github.com/users/y111x/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/y111x/subscriptions",
        organizations_url: "https://api.github.com/users/y111x/orgs",
        repos_url: "https://api.github.com/users/y111x/repos",
        events_url: "https://api.github.com/users/y111x/events{/privacy}",
        received_events_url: "https://api.github.com/users/y111x/received_events",
        type: "User",
        site_admin: false,
        score: 1
      },
      {
        login: "yyxx828",
        id: 56554782,
        node_id: "MDQ6VXNlcjU2NTU0Nzgy",
        avatar_url: "https://avatars1.githubusercontent.com/u/56554782?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/yyxx828",
        html_url: "https://github.com/yyxx828",
        followers_url: "https://api.github.com/users/yyxx828/followers",
        following_url: "https://api.github.com/users/yyxx828/following{/other_user}",
        gists_url: "https://api.github.com/users/yyxx828/gists{/gist_id}",
        starred_url: "https://api.github.com/users/yyxx828/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/yyxx828/subscriptions",
        organizations_url: "https://api.github.com/users/yyxx828/orgs",
        repos_url: "https://api.github.com/users/yyxx828/repos",
        events_url: "https://api.github.com/users/yyxx828/events{/privacy}",
        received_events_url: "https://api.github.com/users/yyxx828/received_events",
        type: "User",
        site_admin: false,
        score: 1
      },
      {
        login: "yyxtysd",
        id: 15401490,
        node_id: "MDQ6VXNlcjE1NDAxNDkw",
        avatar_url: "https://avatars2.githubusercontent.com/u/15401490?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/yyxtysd",
        html_url: "https://github.com/yyxtysd",
        followers_url: "https://api.github.com/users/yyxtysd/followers",
        following_url: "https://api.github.com/users/yyxtysd/following{/other_user}",
        gists_url: "https://api.github.com/users/yyxtysd/gists{/gist_id}",
        starred_url: "https://api.github.com/users/yyxtysd/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/yyxtysd/subscriptions",
        organizations_url: "https://api.github.com/users/yyxtysd/orgs",
        repos_url: "https://api.github.com/users/yyxtysd/repos",
        events_url: "https://api.github.com/users/yyxtysd/events{/privacy}",
        received_events_url: "https://api.github.com/users/yyxtysd/received_events",
        type: "User",
        site_admin: false,
        score: 1
      }
    ]
  });
});

app.listen(3000, "localhost", err => {
  if (err) {
    console.log(err);
    return;
  }
  console.log("服务器启动成功~");
});
